elasticsearch:
  build: elasticsearch/
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - 9200:9200
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - 5601:5601
  links:
    - elasticsearch
fluentd:
  build: fluentd/
  volumes:
    - /home/data/mnt/docker/containers:/var/lib/docker/containers
  links:
    - elasticsearch
  ports:
    - 24224:24224
nginx:
  build: nginx/
  links:
    - fluentd
    - node_app
  ports:
    - 89:80
  log_driver: 'fluentd'
  log_opt:
    fluentd-address: fluentd:24224
    fluentd-tag: docker.{{.FullID}}
node_app:
  build: node_app/
  links:
    - fluentd
  ports:
    - 8089:8080
  log_driver: 'fluentd'
  log_opt:
    fluentd-address: fluentd:24224
    fluentd-tag: docker.{{.FullID}}
