elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - 9200:9200
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - 5601:5601
  links:
    - elasticsearch
fluentd:
  build: fluentd/
  volumes:
    - /home/data/mnt/docker/containers:/var/lib/docker/containers
  links:
    - elasticsearch
  ports:
    - 24224:24224
